### PR TITLE
Added resource efficient opting-out

### PR DESCRIPTION
**Pull request by ghost**
you

### CODE REVIEW

**Comment by RGBCube** [comment]
based

**Comment by AAGaming00** [comment]
WTF IS THIS WHY ARE YOU USING JSON WHEN IT HAS SQL INSANE

**Comment by mantikafasi** [comment]
guhhh because I told him to do like that, since there wont be much people that want to be opted out I thought making sql requests on every request was stupit

**Comment by RGBCube** [comment]
just cache it dumb

**Comment by mantikafasi** [comment]
too lazy to test,lets try it on real server

**Comment by RGBCube** [comment]
:trollface:

**Pull request merged**
